apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- aggregator-sa.yaml
- aggregator-deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: application-config-schema
  files:
  - schema.json=schema.json
