apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base
  - rbac

images:
  - name: quay.io/numaio/numalogic-config-aggregator
    newTag: latest

namespace: numalogic-argorollouts