apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-aggregator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-aggregator-role
subjects:
  - kind: ServiceAccount
    name: config-aggregator-sa
