apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: numalogic-config-aggregator-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
